export const RULES_TOTAL_SET_MAX_INCREASE_VALUE = 0
export const RULES_TOTAL_SET_MIN_INCREASE_VALUE = 1
export const RULES_TOTAL_SUM_INCREASE_VALUES = 2
export const RULES_TOTAL_SET_MIN_NON_ZERO_INCREASE_VALUE = 3

export const PRODUCT_INCREASE_STRATEGY_MAX = 0
export const PRODUCT_INCREASE_STRATEGY_MIN = 1
export const PRODUCT_INCREASE_STRATEGY_SUM = 2
export const PRODUCT_INCREASE_STRATEGY_MIN_NON_ZERO = 3

/*
  Cost increase modes
*/
export const COST_INCREASE_MODE_MAX = 0;
export const COST_INCREASE_MODE_MIN = 1;
export const COST_INCREASE_MODE_SUM = 2;
export const COST_INCREASE_MODE_NON_ZERO_INCREASE = 3;
export const COST_INCREASE_MODE_MIN_NON_ZERO = 4;