/*
  Ruleset resolver
*/
export const RULESET_RESOLVER_SET_POSITION_VALUE = 0;
export const RULESET_RESOLVER_SET_POSITION_ITEM_VALUE = 1;
export const RULESET_RESOLVER_ADD_POSITION_VALUE = 2;
export const RULESET_RESOLVER_ADD_POSITION_ITEM_VALUE = 3;
