export const OPTION_VALUE_IS_ANY = -1

export const RULES_TOTAL_SET_MAX_INCREASE_VALUE = 0
export const RULES_TOTAL_SET_MIN_INCREASE_VALUE = 1
export const RULES_TOTAL_SUM_INCREASE_VALUES = 2
export const RULES_TOTAL_SET_MIN_NON_ZERO_INCREASE_VALUE = 3

export const PRODUCT_INCREASE_STRATEGY_MAX = 0
export const PRODUCT_INCREASE_STRATEGY_MIN = 1
export const PRODUCT_INCREASE_STRATEGY_SUM = 2
export const PRODUCT_INCREASE_STRATEGY_MIN_NON_ZERO = 3

/*
  Ruleset resolver
*/
export const RULESET_RESOLVER_SET_POSITION_VALUE = 0
export const RULESET_RESOLVER_SET_POSITION_ITEM_VALUE = 1
export const RULESET_RESOLVER_ADD_POSITION_VALUE = 2
export const RULESET_RESOLVER_ADD_POSITION_ITEM_VALUE = 3